### ISSUE TITLE
`catalogue.json` not included in source and wheel files

### ISSUE THREAD

**Issue by iyanmv** [ZAdamMac/python-enigma#9]
You can check that in [the package files at PyPI](https://pypi.org/project/python-enigma/#files) there is no `catalog.json` file. I think this file should be included so the class can actually be used with the "default" string.

**Comment by ZAdamMac** [comment]
That's one hell of an oversight on my part! Thanks for pointing it out.

I'm not in a position to make this update immediately but I'll take care of it tonight after work.

**Comment by ZAdamMac** [comment]
This should now be fixed in the version 1.1.3 package, which is currently uploaded at pypi.

I've tested myself on a fresh install in a location without any native copy of the catalog.json, so it's definitely loading the version from the package itself.
